# Generated by Django 5.0.1 on 2024-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
