# Generated by Django 5.0.1 on 2024-02-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
